version: '3'
services:
  directus:
    container_name: tech-blog-directus
    image: directus/directus:10.0.0
    ports:
      - "8055:8055"
    volumes:
      - ./uploads:/directus/uploads
      - ./extensions:/directus/extensions
      - ./snapshots:/directus/snapshots
    environment:
      KEY: 'change-me-to-a-unique-key'
      SECRET: 'change-me-to-a-unique-secret'
      DB_CLIENT: 'mysql'
      DB_HOST: 'mysql'
      DB_PORT: '3306'
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      DB_PASSWORD: 'directus'
      ADMIN_EMAIL: 'admin@example.com'
      ADMIN_PASSWORD: 'change-me-to-a-secure-password'
      CORS_ENABLED: 'true'
      CORS_ORIGIN: '*'
    depends_on:
      - mysql
    restart: unless-stopped

  mysql:
    container_name: tech-blog-mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 'root-password'
      MYSQL_DATABASE: 'directus'
      MYSQL_USER: 'directus'
      MYSQL_PASSWORD: 'directus'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  mysql_data:
    driver: local